### ISSUE TITLE
Can't connect to server that perform SSL client certificate verification

### ISSUE THREAD

**Issue by estan** [mattermost/mattermost-mobile#1495]
#### Summary

Trying to connect to a server that performs SSL client certificate verification using the Android app gives the error "Cannot connect to the server. Please check your server URL and Internet connection.".

Connecting through a mobile browser like Chrome works (pops up a dialog asking for the client certificate).

#### Environment Information

- Device Name: Sony Xperia Z5 Compact
- OS Version: Android 7.1.1
- Mattermost App Version: 1.6.1
- Mattermost Server Version: 4.2.0

#### Steps to reproduce

Try to connect to a server that performs SSL client certificate verification using the Android app.

#### Expected behavior

Should be able to log in.

#### Observed behavior

Android app gives the error "Cannot connect to the server. Please check your server URL and Internet connection.".

**Comment by law** [comment]
Same here.

**Comment by estan** [comment]
To Mattermost devs: See [this](https://github.com/facebook/react-native/issues/10885#issuecomment-260070604) comment for what needs to be done, until [this](https://react-native.canny.io/feature-requests/p/support-tls-client-certificate-authentication-in-fetch-api-implementation) React Native feature request is taken care of.

**Comment by amyblais** [comment]
Hi @estan, This has been discussed with our engineers - it seems that the client certificate verification that you are trying to use is not supported yet. There are plans to add the support in the future but it will be an Enterprise Edition E20 feature and only available on iOS.

Closing this issue for now,

**Comment by estan** [comment]
@amyblais I know it's not supported, that's why I reported the issue. Could you please motivate your decision, since I'm having a hard time understanding it. It's a plain defect in the software that prevents its use in many environments. Client certificate verification is an integral part of the SSL specification. This is not a feature request but a defect report.

The fact that you're planning to make this an EE "feature" only is even more worrying. Does this mean you would not accept a PR from me (or someone else) to fix this in the open source edition?

**Comment by amyblais** [comment]
Re-opened this ticket as this has been queued for further team discussion.

**Comment by estan** [comment]
@amyblais Thanks a lot, and sorry if I sounded a little harsh. The best solution would be if React Native could support this in its `fetch` API. I think any changes needed to Mattermost Mobile would then be small.

**Comment by amyblais** [comment]
No worries at all! This is an important issue to discuss further with the team, thank you for bringing it to our attention.

**Comment by jasonblais** [comment]
Hi @estan @law! First, thanks for using the Mattermost mobile apps!

There are in fact two types of client-side certificate authentications in play here.

1) SSL client certificate via TLS mutual auth for client/device authentication. This is not yet supported in the mobile apps as you've identified. I believe this is what you are referring to?

We are tracking this [feature proposal here](https://mattermost.uservoice.com/forums/306457-general/suggestions/14756865-mobile-client-ssl-authentication). I encourage you to contribute to the feature proposal by upvoting it, as we regularly monitor that forum. You get **10** votes, and each one influences the future of the project.

2) The other feature we're building is certificate based auth (CBA) for user authentication, for instance through Purebred integration. This is a very specific, customer request to meet compliance requirements, which is why it's considered for Enterprise Edition. However, it is different from SSL client cert verification mentioned in 1).

Let me know if you guys have any further questions, would be happy to clarify any points :)

**Comment by jasonblais** [comment]
@estan Perfect, sounds good. I'll close this issue off for now and we can track through the feature proposal.
