### ISSUE TITLE
Disconnection without notice, requiring app restart to send messages

### ISSUE THREAD

**Issue by iGeekFace** [mattermost/mattermost-mobile#1647]
#### Summary
Randomly the Android app will silently disconnect, meaning that it isn't connected but there is no message indicating that it isn't connected. When this occurs, I'm unable to post messages even after several attempts. To resolve it, I need to restart the app, but doing so causes any messages I sent that didn't successfully post to disappear, so I need to retype them.

#### Environment Information

- Device Name: OnePlus 5T
- OS Version: 8.0.0
- Mattermost App Version: 1.8.0
- Mattermost Server Version: 4.9.1

#### Steps to reproduce
I believe it may occur while switching cell towers or networks. You could go for a long walk while using Mattermost.

#### Expected behavior
Stay connected or indicate that a disconnection has occurred. Save unsent message after app restart so that it can be resent.

#### Observed behavior
See summary above.

#### Possible fixes
Not sure.

**Comment by zoobiaashfaq43** [comment]
Same happened with me. I am also not receiving any notification from mattermost on my Andiod app. Like I have to check the app to see if I have any notification/message.

**Comment by lindy65** [comment]
Hi @iGeekFace @zoobiaashfaq43 

Thanks for the report,

I've created a ticket [here](https://mattermost.atlassian.net/browse/MM-10408) for us to investigate and try to reproduce...

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the above-linked ticket.

**Comment by etursunbaev** [comment]
@lindy65 Above ticket is closed, so writing here.
Issue is actual. Mattermost mobile app on android disconnects when it is minimized or in standby mode in a background. If you need more information I can provide

**Comment by lindy65** [comment]
Hi @etursunbaev :)

Thank you for the report!  As this issue is old and we weren't able to reproduce it on our team when it was opened last year (see [ticket](https://mattermost.atlassian.net/browse/MM-10408)) would you please open a new issue so we can reproduce it with what you're seeing now?

Please let us know which version on the Android App you are using as well as which Mattermost server you are running.  You can find this by going to 3-dot menu > Settings > About Mattermost.

Please also give us the exact steps of how you reproduce this so we can try to reproduce it in our team.

Thank you!
