### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by vukhanhtruong** [mattermost/mattermost-mobile#1720]
Hello,

#### Summary
Everything works fine after upgrading, but the mobile app.
Also, the logs section in the console, it shows nothing.

#### Environment Information

- Device Name:  Xiaomi Redmi Note 4X
- OS Version: 7.0 NRD90M
- Mattermost App Version:  1.8.0
- Mattermost Server Version: 4.10.0

#### Steps to reproduce
Input Server URL.
Hit `Connect` button.
It says "Cannot connect to the server".

#### Expected behavior
Works fine like before

Please help me out. Thanks in advance.
Regards,

**Comment by amyblais** [comment]
Hi @vukhanhtruong! Thank you for reaching out.

As a first step, we recommend checking with your System Admin to validate the SSL chain for your server. Please let me know any questions.

**Comment by vukhanhtruong** [comment]
Hi,

I've just renewed SSL using Letsenscrypt. 
I was double check on ssllabs.com, you can see the result here https://ibb.co/bK3nq8
So, Could you please give me more detail how to solve this issue. 

I really appreciate your support.
Thank you very much.

**Comment by amyblais** [comment]
Hey @vukhanhtruong, thank you for the additional information.

Here are some additional tips/questions:

1. Can you help share an example of the URL you are using to connect via your phone?
2. Have you tried uninstalling and reinstalling the app to see if it helps?
3. Can you try connecting to https://pre-release.mattermost.com and see if you hit the same issue?
4. What happens if you try and open the url with the mobile browser?
5. Are you using nginx in front as reverse proxy? If yes, can you share the config file?
6. Can you take a look at these tips and see if any helps: https://github.com/mattermost/mattermost-server/issues/7440#issuecomment-335783004?

Let me know if any of the above helps!

**Comment by vukhanhtruong** [comment]
Hey,

Thanks for your kindly support. Here are my answers:
1. It would be nice if you could send me an email to [me](mailto:vukhanhtruong@gmail.com) using your own email address, then I can share the URL privately.
2. Yes, I did.
3. It works, no issue
4. My URL is working fine with the mobile browser
5. I'm using the Mattermost docker https://github.com/mattermost/mattermost-docker

Best Regards,

**Comment by amyblais** [comment]
Hi @vukhanhtruong!

Thank you for the additional information, I just sent you an email regarding point 1.

**Comment by amyblais** [comment]
Ah, I just realized you were seeing the issue on Android (I only have iOS), so I will ask a teammate to help test this tomorrow. I will forward the URL you sent to me earlier today privately to a colleague.

**Comment by amyblais** [comment]
A colleague tested this and he is seeing the same issue with the URL that you provided.

@enahum The user is unable to connect to server on Android 1.8 (doesn't repro on pre-release or any other devices/browsers) - do you see anything in the license that could be an issue: https://ibb.co/bK3nq8?

**Comment by enahum** [comment]
Yeap, as you can see in the screenshot it says that the SSL has chain issues, those need to be corrected and then it should be ok

**Comment by vukhanhtruong** [comment]
@enahum Why the mobile app on iOS still works? Thanks for the kind support.

**Comment by enahum** [comment]
@vukhanhtruong as you can see in the screenshot your certificate has an incomplete chain, is not a matter of a new key or not, is probably that you need an intermediate certificate.

perhaps take a look at https://letsencrypt.org/certificates/ and https://letsencrypt.org/2015/06/04/isrg-ca-certs.html for more info

![image](https://user-images.githubusercontent.com/6757047/41299519-99c18e82-6e31-11e8-919e-7ce440d18fdf.png)

**Comment by amyblais** [comment]
Hi @vukhanhtruong, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
