### ISSUE TITLE
How can I build and run this app on window 10

### ISSUE THREAD

**Issue by anhhangxom0610** [mattermost/mattermost-mobile#1983]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
 Unable to resolve module `app/actions/views/login`  on window 10
#### Environment Information

- Device Name: MI LTE4
- OS Version: Window 10
- Mattermost App Version: Lastest
- Mattermost Server Version:Lastest

#### Steps to reproduce
How can we reproduce the issue?

#### Expected behavior
error: bundling failed: Error: Unable to resolve module `app/actions/views/login` from `D:\Source\mattermost-mobile-master\mattermost-mobile-master\app\mattermost.js`: Module `app/actions/views/login` does not exist in the Haste module map. 
I have built and run this on window 10. But it always return some issues like that. I have tried many time to clear cache node but it still happens. How can I fix this, plz? Thanks guys

**Comment by enahum** [comment]
Node and npm version?

**Comment by amyblais** [comment]
Hi @anhhangxom0610, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
