### ISSUE TITLE
Symbols +, - and *, when alone on the line, are rendered as empty unordered list element

### ISSUE THREAD

**Issue by WGH-** [mattermost/mattermost-mobile#2077]
#### Summary
Mobile Mattermost client renders symbols `+`, `-`, and `*`, when they're alone on the line, as empty unordered list element, which deviates from Mattermost web client behaviour.

#### Environment Information

- Device Name: Redmi Note 4
- OS Version: Android 7.1.2
- Mattermost App Version: 1.11.0 (Build 133)
- Mattermost Server Version: 5.0.0

#### Steps to reproduce
Send message containing either just `+`, `-`, or `*`.

#### Expected behavior
I expected that the behaviour of Mattermost mobile and the web version would be more or less the same.

#### Observed behavior
Mobile version above, web version below:

![image](https://user-images.githubusercontent.com/1099351/45056409-74c09e00-b09b-11e8-8486-f57ce1dd8a1b.png)

![test](https://user-images.githubusercontent.com/1099351/45056452-a0438880-b09b-11e8-949b-46c978bbe4e4.png)

#### Possible fixes
I think that the web behaviour is correct, and the mobile behaviour is wrong. When user posts `+` on a separate line, he likely doesn't want an empty unordered list element.

**Comment by hmhealey** [comment]
Hi @WGH-,

Thanks for the report. While I agree that it would probably make more sense to just show the character like it does on the web app, we're moving towards following the [CommonMark](https://commonmark.org/) spec to match up with other services like GitHub, and CommonMark renders an empty list item in those cases.

We do plan on having the web app follow that as well by switching it to use the same library as the mobile app. The ticket is [here](https://mattermost.atlassian.net/browse/MM-10003) if you're interested in following it. I'll note this case in the ticket so that we can make sure it works the same on both platforms once that's done.

**Comment by hmhealey** [comment]
One other thing, if you do want just a single one of those characters, you can escape it with a backslash like `\+`.
