### ISSUE TITLE
Mattermost Android Connection issues

### ISSUE THREAD

**Issue by phoenixrizen001** [mattermost/mattermost-mobile#2139]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
I am having an issue connecting to mattermost server with the android app. 

#### Environment Information

- Device Name: Samsung Note 8 
- OS Version: 8.0.0
- Mattermost App Version: 1.12.0
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
not sure if it is my config but it works on one connect. 

#### Expected behavior
When I open the app on the phone I put my server url and it does not connect. get the error "Cannot connect to the server. Please check your server URL and internet connection"

#### Observed behavior
If I place my server URL, I get the error but if I use https://pre-release.mattermost.com I get the login. I backup then put in my server URL and it accepts it with no issue. If the app gets closed then I have do the process all over again with the pre-release url then my server url

**Comment by amyblais** [comment]
Hi @phoenixrizen001, thanks for reaching out 👍 

Can you help take a look at this section of our troubleshooting docs and see if it helps: https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection?

**Comment by ElNovi** [comment]
I can confirm this, connection worked all right. But people can't connect to Mattermost after updating to 1.12.0.

We are using Gitlab omnibus deployment and our current version of Mattermost is 5.1.1

**Comment by amyblais** [comment]
Hi @ElNovi,

Can you help take a look at this section of our troubleshooting docs and see if it helps: https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection?

**Comment by ElNovi** [comment]
Hi @amyblais,

I did look at that, but it didn't help.

Those who didn't update their mobile app are still able to connect to server.

**Comment by amyblais** [comment]
@ElNovi, Can you help with more details on your environment and can you also help share a link to your server and we can test it out?

**Comment by phoenixrizen001** [comment]
Hi @ElNovi 
do you happen to have the old apk file for Android?

**Comment by ElNovi** [comment]
@phoenixrizen001 Thanks for advice 😄 I found the previous version here https://apkpure.com/mattermost/com.mattermost.rn and it's working with the old version 🙂 

@amyblais As i said it's Gitlab Omnibus, Mattermost version is 5.1.1, Gitlab is 11.2.3 and authentication to Mattermost is done through Gitlab. Phones used vary in Android version and phone manufacturer. I can send you our address via some private message.

**Comment by amyblais** [comment]
@ElNovi You can find me at our [Community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) as `amyblais` or you can email me at `amy.blais@mattermost.com`.

**Comment by phoenixrizen001** [comment]
@ElNovi, Do you happen to know which apk version works?

**Comment by ElNovi** [comment]
@phoenixrizen001 Yes the previous one 1.11.0

**Comment by amyblais** [comment]
Hi @ElNovi, our QAs tested this and they are seeing the same issue. Can you help share the results of ssllabs.com so we can take a look if there's any issues? We also recommend not using self-signed certificates (not sure why it's working on v1.11).

**Comment by amyblais** [comment]
Hi @phoenixrizen001, can you help share the results from ssllabs.com and we can take a look if there's any issues?

**Comment by ElNovi** [comment]
Hi @amyblais I don't think this is related to the certificate. It worked well from 1st january 2017 until now. The reason why it worked with self-signed certificate is that that everyone has installed our root certificate on their Android or iOS devices.

When you don't have our company certificate it will tell you right away that the connection can't be established. But now with 1.12.0 it tries to connect and will time out after few minutes. Is there a way how i can debug your mobile app, to see what's wrong?

**Comment by amyblais** [comment]
Hi @ElNovi @phoenixrizen001 I asked our developers about this and they also want to see the ssllabs.com reports, can you help send them over?

**Comment by phoenixrizen001** [comment]
@amyblais Where would you like me to send them? to your email?

**Comment by amyblais** [comment]
@phoenixrizen001 The cert has issues that need to be resolved - the ssl report shows that the chain is incomplete. Our devs confirmed this.

@ElNovi Unfortunately we cannot test the cert as it is a self-signed cert and we don't have the root cert, so we recommend using Let's Encrypt.

**Comment by r00tbox** [comment]
I have the same issue, it just stopped working with 1.12.0 and is still working with 1.11.0.

**Conclusion is that at least one change in 1.12.0 broke your it!** We use AlphaSSL Certificate.

**Comment by amyblais** [comment]
Hi @r00tbox, can you help share the results from ssllabs.com and we can take a look if there's any issues in your cert?

**Comment by phoenixrizen001** [comment]
@amyblais you are correct, I installed the intermediate certs and it works like a charm.  Thank you

**Comment by r00tbox** [comment]
No pls reopen this, this still exists!

@amyblais sorry i can't deliver this because ssllabs only allows default ports and we don't use default ports.

anyway i have intermediate installed and this works with 1.11.0 but not with 1.12.0! Pls let me know what kind of information you need.

Did you change anything according to the certificate check? This should be a point to check for your devs!

**Comment by amyblais** [comment]
@r00tbox You mentioned you're using AlphaSSL Certificate, is that a self-signed / client certificate?

**Comment by r00tbox** [comment]
No it's not a self signed certificate. We use a commercial wildcard certificate from them.

**Comment by amyblais** [comment]
@r00tbox Can you help check if another SSL server test page might work to check the certificate, e.g. https://www.sslshopper.com/ssl-checker.html? The first step in troubleshooting connection errors like this is to check whether there are any issues with the certificate, and usually fixing those issues is the easiest solution.

**Comment by brycied00d** [comment]
I've also been suffering since the 1.12.0 release and I'm happy to see I'm not alone.

Our setup:
* Internal Mattermost server. (Cannot provide the output from SSL checker or similar tools)
* Internal certificate authority, installed + trusted by the phone.
  Confirmed trusted as Chrome has no problems accessing and using the web interface. And the CA is listed in the device's user-installed credentials, Settings -> Security -> Credential storage -> Trusted credentials -> User.
* There are no intermediate CAs - the server's certificate is signed directly by the CA.
* Device is OnePlus 3T OP3T_O2_BETA_30 (Android 8.0.0) (Other users in my company have also reported this issue, but I don't have in-depth information on their deviecs.)

ADB logcat didn't output anything from attempting to connect.
Wireshark of the connection is much more interesting.
* Shows 4 connection attempts when I pressed "Connect" (retry logic, I presume)
* Every connection followed as such:
  * Phone -> **Server**: Client Hello
  * **Server** -> Client: Server Hello
  * **Server** -> Client: Server Key Exchange
  * Client -> **Server**: TLS Alert "Certificate Unknown"
  * Client closes the connection.

Based on my analysis, `com.mattermost.rn` either does not use Android's certificate storage, or it's ignoring user-installed certificate authorities.

I looked at the [changes between 1.11.0 and 1.12.0](https://github.com/mattermost/mattermost-mobile/compare/v1.11.0...v1.12.0) and I didn't see any mention of changes in connection handling. Perhaps I missed something (I'm not very familiar with mobile app development). Perhaps this change came from one of the external components? 

I hope this helps track down what changed and produces a fix!

**Comment by brycied00d** [comment]
I did a bit more digging, determined that the Mattermost Android (and iOS, I gather) apps use react-native and Googled for a similar issue. I think this issue may be caused by https://github.com/facebook/react-native/issues/20488 

I noticed that the AndroidManifest.xml does not specify a "network configuration block", and I wonder if the change in c24492be8f7f9f64e0a2d18f4a670e98494cc3f4 undid some sort of compatibility that was shoe-horning that behavior (use of system and user CA storage) back into the Android build.

Anyways, I'm far from an expert on this, just trying to pin down what kind of change may have altered behavior and offer a possible solution.

**Comment by piemonkey** [comment]
I'm seeing this problem and I'm using a Let's Encrypt certificate. I haven't had much chance to do much digging but since the app is RN I'll take a closer look when I can.

At the moment I suspect that the app is ignoring the https in the url as I'm seeing a request in the nginx logs which returns a 301. I'm using the docker production set-up, hosted on own network using duckdns and with my own Let's Encrypt set-up using Dehydrated.

**Comment by bbodenmiller** [comment]
Based on the whole idea of people running Mattermost on their own servers I assume many of your users have custom root CAs that are installed on computers & phones. Based on https://github.com/facebook/react-native/issues/20488#issuecomment-409535369 it sounds like some additional configurations need to be added to the app to once again support user installed CAs since the update to Android SDK 26.

**Comment by amyblais** [comment]
Hey all, would anyone be interested to submit a PR to fix this based on ``bbodenmiller's`` discovery above ^ ?

**Comment by piemonkey** [comment]
For anyone reading this who's using Let's Encrypt, for me it was a problem with the certificate chain, all I needed to do was point the Mattermost nginx config's `ssl_certificate` at the `fullchain.pem` generated by, in my case, Dehydrated. I'm now able to connect to it.

@amyblais I'm not using a self-cert, but given how simple this looks I could probably throw in a PR. You mentioned before that the devs were hesitant to allow these certs for security reasons, does this still not apply?

**Comment by bbodenmiller** [comment]
@piemonkey I believe the trusty flag they didn't want to add is different than the details I added above. The details above would just allow the app to continue working as it did in SDK 25 & above as it relates to CAs.

**Comment by amyblais** [comment]
@piemonkey Yes, I believe PR in this case is find 👍

**Comment by amyblais** [comment]
Following up on if anyone has any questions on this if they are working on a fix for this issue?

**Comment by neeeeds** [comment]
Hi all, any help with this problem ? since tune update of the app i can't connect to our framateam server. thank you.

**Comment by amyblais** [comment]
Hi all, our developers just submitted a fix for this here: https://github.com/mattermost/mattermost-mobile/pull/2301
