### ISSUE TITLE
Weird scrolling bug in Android 9

### ISSUE THREAD

**Issue by cburschka** [mattermost/mattermost-mobile#2213]
#### Summary
When scrolling the message pane, the scroll direction reverses after you let go.

#### Environment Information

- Device Name: Pixel
- OS Version: 9
- Mattermost App Version: 1.12.0 (142)
- Mattermost Server Version: 5.3.0 (Build 5.3.1)

#### Steps to reproduce
Open any channel/conversation history, and swipe rapidly down (to scroll up to older messages) or up (to scroll down to newer messages). Then let go of the screen.

#### Expected behavior
After letting go, the pane continues moving in the same direction, gradually slowing down.

#### Observed behavior
After letting go, the pane begins to move in the opposite direction. This effect can only be avoided by coming to a complete stop before letting go of the screen.

#### Possible fixes
Not sure, but I'm guessing there's a sign error somewhere.

**Comment by amyblais** [comment]
Hi @cburschka, this issue will be fixed in v1.13 - here are links to the fixes for reference:

-https://mattermost.atlassian.net/browse/MM-12273
-https://github.com/mattermost/mattermost-mobile/pull/2161

If you want to, you can sign up for [beta testing](https://play.google.com/apps/testing/com.mattermost.rnbeta) and then download the latest app version from Google Playstore. It includes a fix for this scrolling issue and community members have reported that it works.

**Comment by cburschka** [comment]
Thanks very much! I'll be using the beta version for now, which seems to be working well so far.
