### ISSUE TITLE
Notification preferences not saved

### ISSUE THREAD

**Issue by paddatrapper** [mattermost/mattermost-mobile#2334]
#### Summary
Changing email/push notifications in the android app, does not update the user's notification preferences. 

#### Environment Information

- Device Name: Android 
- OS Version: 8.1.p
- Mattermost App Version: 1.13.0
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Disable email notifications within the app and wait for a notification. 

#### Expected behavior
The notification should not send an email

#### Observed behavior
Email sent to the user's email address. Notifications in the app still reflect the new preferences (no email), but the web-app does not.

**Comment by enahum** [comment]
Hi @paddatrapper are you sure the preferences are not updated or they are just out of sync, I know they could be out of sync cause of the preferences update not being sent throw the websocket, can you confirm by reloading the webapp after making the changes in the mobile app?

Thanks.

**Comment by amyblais** [comment]
Hi @paddatrapper, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
