### ISSUE TITLE
Can't run iOS app on simulator

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2407]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Failed to load bundle while running on iOS simulator

#### Environment Information

- Device Name: iPhone Simulator
- OS Version: 11.1
- Mattermost App Version: 1.14.0 (commit `aa41579f` from github)
- Mattermost Server Version: <don't know>

#### Steps to reproduce
Build the iOS code with node 9.3.0 and npm 6.4.1.
Run from Xcode or from command line with `make run-ios`

#### Expected behavior
App launches and works.

#### Observed behavior
Getting failed to load bundle error:

![image](https://user-images.githubusercontent.com/350654/49262639-88618200-f49b-11e8-808f-167c979bc927.png)

**Comment by mgrebenets** [comment]
While trying to run `Release` configuration I get an error due to missing `main.jsbundle`.
And the file is missing because "Bundle React Native code and images" build phase failed.
It failed due to the same issue: `Unale to resolve module `mattermost-redux-client`.
I'm not sure what could be wrong here, since `make pre-run` finished successfully.

**Comment by mgrebenets** [comment]
Found reference to similar issue here https://github.com/mattermost/mattermost-mobile/issues/2303
Since I couldn't get stable package install from `npm`, I tried `yarn`.

`yarn` is much better when it comes to installing packages.
However, even when using `yarn install` and then `yarn start -- --reset-cache` I get same error as on screenshot.

One part that's confusing to me is why does it say "share_extension/android/index.js" even though I'm building for iOS?

**Comment by enahum** [comment]
The problem here is that mattermost-redux builds itself during the prepare script, seems for some reason npm sometimes failed to run the prepare script, we are looking for other alternatives. As a workaround you can `cd node_modules/mattermost-redux` and run npm install in that directory for it to build properly, also maybe try with node 10, in my case I have node 10.11.0 and npm 6.4.1 and it works fine every time

@hmhealey this is what I was talking about the other day, and now it seems is not only happening on the ci
