### ISSUE TITLE
App crash with specific message

### ISSUE THREAD

**Issue by dabbill** [mattermost/mattermost-mobile#2412]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Specific message can crash app.

#### Environment Information

- Device Name: 
- OS Version: Android 8.0.0 Sept 1st 2018 security update
- Mattermost App Version: 1.14.0
- Mattermost Server Version: 5.4 (gitlab bundle)

#### Steps to reproduce
How can we reproduce the issue?
Send message to any channel with the following.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#### Expected behavior
View message with out app crashing.

#### Observed behavior
Application totally locks up and unable to do anything by wait for android popup to foce close the app. Deleting the message from desktop app, and clearing cache on mobile device makes app function again. 

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @dabbill,

Thank you for the report, I'll start by testing this out on iOS as I don't have Android. If I can't reproduce this then I'll ask one of our QAs to test it out on Android in case it is Android specific issue.

**Comment by dabbill** [comment]
I am on T-Mobile LG G7 ThinQ.

**Comment by hmhealey** [comment]
I think I see what's happening here since I actually fixed it already, but I didn't realize that change wasn't included in 1.14. Certain characters trigger the Markdown renderer to start a new text node so while `I'm using Markdown` might render as `<Text>I'm using Markdown</Text>`, `!!!` might render each as its own Text node so you get `<Text>!</Text><Text>!</Text><Text>!</Text>`. It looks like Android just has problems when you have a lot of Text nodes on screen at once.

Thankfully, that's actually fixed on master already since that was causing some problems when I was adding code to highlight mention keywords, so it should already be fixed for 1.15.

**Comment by dabbill** [comment]
Awesome. Thanks for the updates  :-)

-----Original Message-----
