### ISSUE TITLE
Too many url requests

### ISSUE THREAD

**Issue by Robbe7730** [mattermost/mattermost-mobile#2507]
#### Summary
When there are urls in a direct message, the app queries them all at the same time, causing spam filters to trigger.

#### Environment Information

- Device Name: Huawei P20 Lite
- OS Version: Android 8.0.0
- Mattermost App Version: 1.15.1 (Build 166)
- Mattermost Server Version: 5.6.0 (Build 5.6.2)

#### Steps to reproduce

- Make sure a spam filter (like fail2ban) running on the server that runs the Mattermost server
- Enable a filter that prevents script-scanning (like nginx-noscript for fail2ban)
- Send multiple direct messages with a URL (>10)
- Open the direct messages on the mobile app

#### Expected behavior

There seems to be no delay when looking up urls. This caused our server's spam detection to trigger and caused an IP-ban for too many requests. Also, the url is not on the Mattermost server, but an external site. (Why is it querying these anyway?)

#### Observed behavior

A lot of requests to  /api/v4/redirect_location?url=(URL), even though this is an external URL.
```
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 483 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 483 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 482 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 482 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 483 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 483 "-" (Client info)
X.X.X.X - - [14/Jan/2019:00:43:48 +0100] "GET /api/v4/redirect_location?url=(URL) HTTP/2.0" 200 483 "-" (Client info)
```

#### Possible fixes
No idea, possibly even mattermost-redux?

**Comment by enahum** [comment]
It seems there is a PR for this https://github.com/mattermost/mattermost-server/pull/10118

**Comment by hmhealey** [comment]
Hi @Robbe7730,

The reason this happens is because the app is looking at the external link to find content that it can show as a preview. When it hits that particular endpoint, it's checking to see if the link is from a link shortener like bit.ly.

In addition to the PR linked by @enahum, we're also doing further work to have the server be in charge of making those requests (right now, it does it whenever the client asks it to) and to add even better caching of that data on the server, so you'll see even fewer of those requests.

**Comment by hmhealey** [comment]
In the mean time though, there's no easy way to prevent those requests without modifying the code of the app. If you're looking to do that, I can point you to what needs to be disabled to turn that behaviour off

**Comment by Robbe7730** [comment]
Thanks for the reply. However, I think the problem is not server-side, but the app sending too many requests to the server, so improving caching on the server will not fix this problem, unless this behaviour is shifted to the server completely.

Other options are for example keeping a cache on the app itself, to only send one request to the server per URL instead of one per message containing a URL. This would however not fix the problem if the channel has many different URLs...

If you could give me some idea where I can find the code related to this, I'll have a look to see what could be a good solution.

**Comment by hmhealey** [comment]
The actual call to that API is done [here](https://github.com/mattermost/mattermost-mobile/blob/master/app/components/post_body_additional_content/post_body_additional_content.js#L127) where it's looking to see what preview should be displayed by the client.

Looking at that component, you're absolutely right that it doesn't do any sort of caching on the potentially-expanded link, so it make the same request each time you see the same post. I think the best way to deal with this would be to store those expanded links in the redux store. I'm not sure how experienced you are with redux, so I can give more information on this if you'd like, but the general idea would be to create a new reducer (probably in `app/reducers/views/channels.js`) that watches for the `REDIRECT_LOCATION_SUCCESS` action dispatched by `getRedirectLocation` and uses it to store the expanded link. The component can then check if the expanded link exists in the redux state before actually calling `getRedirectLocation` a second time.

Alternatively, if you're only wanting this for a custom build, you could just remove the call to `getRedirectLocation` entirely since the only thing that you'll lose from it will be link previews for shortened links. Once that additional work I mentioned before is done, `getRedirectLocation` won't be used any more anyway, so you'll get shortened link previews back as well

**Comment by Robbe7730** [comment]
I've used redux before, so I'll look into it soon. Do we also want to store when the request is pending? I assume the requests happen asynchronous, so another request could be sent to the server while the previous one is still pending. This could be done by watching for the `REDIRECT_LOCATION_REQUEST` action, but that then needs to send the url it's requesting in its `data`-field. 

If we do that, what should happen if a `REDIRECT_LOCATION_FAILURE` action happens? Should the next url retry, or assume it's going to fail too?

**Comment by hmhealey** [comment]
I don't think we really need to store when there's already a request pending since it would probably be rare that the same link is posted twice in a short period of time, and even if it is, I don't think that would help since the redux state probably wouldn't be updated in time to prevent the second request.

Watching for failure makes sense though so we know not to make the request again. Perhaps we just have it store the original URL as the expanded one instead of adding a special error case.

Also, I just realized that this will require some changes to the `mattermost-redux` side as well since it only dispatches with the expanded URL, so you won't be able to determine what the original URL was without adding that as well.

**Comment by Robbe7730** [comment]
That's true, altough I'm not convinced on storing the failed url as the expanded one. Maybe there was a temporary problem getting the expanded URL, but it does work after some time. The app wouldn't know it did not work.

Also, is the redux state presistent? If so, a url may change to another expanded url after some time. Maybe there could be a TTL by adding a lastChecked?

About the changes in `mattermost-redux`, they don't seem too difficult. There would be some changes in  the [getRedirectLocation](https://github.com/mattermost/mattermost-redux/blob/20962c1cf778b760a2e4c2f2678c1715a93c1328/src/actions/general.js#L186) function, and possibly types in [src/action_types/general.js](https://github.com/mattermost/mattermost-redux/blob/2f7f032e8f4a416e904b38afa4b5834c3263339d/src/action_types/general.js#L51), but I'm not sure how these types work.

**Comment by hmhealey** [comment]
While it's not ideal to store the non-expanded link, I think adding some sort of retry is a lot of effort when the failure case is just that the link preview might not show for shortened links if the network is unstable since those previews are the only reason we actually follow those shortened links.

Redux state is somewhat persistent. I'm not 100% sure on the lifecycle of all of the data, but the app does purge some stuff from time to time.

**Comment by Robbe7730** [comment]
All right, I've got the mobile dev app set up on my pc/phone. I'll see if I can add this :slightly_smiling_face:

**Comment by hmhealey** [comment]
Hi @Robbe7730,

Sorry that this has taken quite some time to get through review. Since we've been doing some other work that will allow us to remove the getRedirectLocation endpoint endpoint entirely, we were actually wondering if you'd be interested in helping finish off those changes. The link for that ticket is [here](https://mattermost.atlassian.net/browse/MM-13807), but basically, the client should already have the expanded link on servers with the new "post metadata" feature enabled, so we shouldn't even need that extra API call.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
