### ISSUE TITLE
Android - share limited to open channels/users

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#2517]
#### Environment Information
- Mattermost App Version: 1.15.2
- Mattermost Server Version: 5.7.0

#### Steps to reproduce
Share an image from gallery app

#### Expected behavior
Press channel, see open channels/chats, use the input field to search for ALL channels/users, choose one/any channel/user on the team that you can access

#### Observed behavior
Search field can search only open channels/users

**Comment by amyblais** [comment]
Hi @licaon-kter,

I asked our QAs about this and the part regarding the share extension to be able to share to all public channels as well as any DM channel has never worked that way (it's currently expected behaviour).

The second part could makes sense to be able to search any user on the server instead of just DM on the sidebar, but being able to search across all public channels does not make sense. It could be that you are mixing open/close with join/leave.

Does this feedback help?

**Comment by amyblais** [comment]
I also opened a ticket for our UX team to take a look: https://mattermost.atlassian.net/browse/MM-13813.

**Comment by amyblais** [comment]
Closing this as there is now a Help Wanted ticket open for this (linked above).
