### ISSUE TITLE
Keyboard lose focus

### ISSUE THREAD

**Issue by FluffyAlpaca** [mattermost/mattermost-mobile#2521]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

I got a flip phone and so, a physical keyboard along with a touchscreen. 
On the physical keyboard, when I type letters, everything's works fine.
When I type special characters, like single quotes or parenthesis, and when I want to go back to typing letters, I lose focus on the text input area and I need to click it again to continue typing.

#### Environment Information

- Device Name: LG Wine Smart
- OS Version: Android 5.1.1
- Mattermost App Version: 1.14.0 (Build 164)
- Mattermost Server Version: 5.6.3

#### Steps to reproduce
How can we reproduce the issue?

Take a phone with a T9 keyboard, type a few letters, then click on "star" ( '*') to access the special chars, type a special char, then click on "sharp" ('#') to go back to the letters section. Instead of going back to the letters section, you will lose focus on the text input area, where you were typing. 

 
#### Expected behavior
Describe your issue in detail.

The focus should remain on the text input area so the user is able to continue typing without having to select the text area manually.

**Comment by amyblais** [comment]
Hi @FluffyAlpaca,

Is this issue similar to https://github.com/mattermost/mattermost-mobile/issues/2512?

**Comment by 2xB** [comment]
Hey, this actually is exactly the same cause as my issue #2512: My issue is caused by a resizing on-screen keyboard and has the same symptoms as yours (loss of focus on resizing keyboard). Nevertheless your last comment documented the problem way better than I did and your example also shows that this is a bug with resizing on-screen keyboards and not a missing feature.

**Comment by FluffyAlpaca** [comment]
Ah indeed, when I go from the digital keyboard to the physical keyboard, I also have the same bug, I didn't notice.
On the following screenshot, I type on my physical keyboard : 
![image](https://user-images.githubusercontent.com/25431347/52045876-b7e94500-2545-11e9-84cb-d49454a10e3f.png)
Then here, I clicked again on the text field to activate the digital keyboard and I typed a letter : 
![image](https://user-images.githubusercontent.com/25431347/52046008-ff6fd100-2545-11e9-8e0e-52331c1e7220.png)
Then I type "#" on my physical keyboard to go back on it, but then it closes completely and I lose focus on the text field:
![image](https://user-images.githubusercontent.com/25431347/52046180-7016ed80-2546-11e9-8460-14831121dafb.png)

**Comment by amyblais** [comment]
Hey all, I asked about this from our team again, and they confirmed that physical keyboards are not officially supported yet. Thanks for creating the Feature request Issues!

**Comment by 2xB** [comment]
Hello, just to be perfectly clear: This is not an issue of physical keyboards. This is an issue of resizing keyboards. Physical keyboards are only one very prominent example I chose for my issue because bugs with them are easy to reproduce. See for example Gboard, the digital keyboard by Google. It has a floating mode, meaning the keyboard disappears and is then drawn above the current application. In any other application I am aware of, after activating the floating mode, one can directly type. In Mattermost, the input field looses focus and the keyboard therefore disappears directly after activating floating mode. One has to then click on the input field again to start typing.
And again: Gboard is no physical keyboard.

**Comment by amyblais** [comment]
I'll ask our team for more details on this,

**Comment by amyblais** [comment]
Hi all, letting you know that I asked our team about this again, and they said that we don't support this yet.

Thanks @2xB for opening the feature request tickets in your previous Github Issue!

**Comment by FluffyAlpaca** [comment]
Alright, thank you for your answers :)
