### ISSUE TITLE
Table is not responsive

### ISSUE THREAD

**Issue by tmdoit** [mattermost/mattermost-mobile#2788]
#### Expected behavior
When switching between portrait and landscape table should resize to the available screen space.

#### Observed behavior
Table has fixed size which doesn't change on changing screen mode.

**Comment by hmhealey** [comment]
Hi @tmdoit.

We used to have something like that, but due to limitations in React Native's layout engine, we had to make the columns of the table use a fixed width to prevent issues with wide tables ([MM-11232](https://mattermost.atlassian.net/browse/MM-11232)).

If you tap on the visible part of the table, it'll open the full table in another screen that's scrollable. Would that solve your problem? I know it's a bit difficult to see that you can do that, so we've also got a ticket ([MM-14199](https://mattermost.atlassian.net/browse/MM-14199)) to improve that as well.

**Comment by tmdoit** [comment]
Opening the table in new window is not an issue for me. The problem is that the table is not resized to the fullscreen.
![signal-attachment-2019-05-14-211406](https://user-images.githubusercontent.com/26081817/57725832-5715f080-768e-11e9-8dae-3549a53ee38a.jpeg)
![signal-attachment-2019-05-14-211416](https://user-images.githubusercontent.com/26081817/57725833-5715f080-768e-11e9-81a5-d7e8433f343e.jpeg)

**Comment by hmhealey** [comment]
Okay, good to know that's what you're looking for. As I mentioned above, we're still limited by React Native's layout engine, but I'll open up a Jira ticket so we can discuss if there's any improvements that we could make here.

https://mattermost.atlassian.net/browse/MM-15635

**Comment by esethna** [comment]
FYI this is opened as a Help Wanted ticket if anyone would be interested in taking this on: https://github.com/mattermost/mattermost-server/issues/11949

Closing so it can be tracked there
