### ISSUE TITLE
Session expire reauth issue

### ISSUE THREAD

**Issue by eljeffeg** [mattermost/mattermost-mobile#3869]
#### Summary
When my session expires and after I log back in, it refuses to connect.  I have to log out and then back in.  I believe this is due to using a client certificate.  I think it's forgetting about the client cert in the session expire / reauth process.

#### Environment Information

- Device Name: iOS
- OS Version: 13.3
- Mattermost App Version: 1.27.1 (Build 260)
- Mattermost Server Version: 5.18.0 (Build 5.18.2)

#### Steps to reproduce
Setup server to require client certificate.  Log in with iOS client and cert.  Let the session time period expire, which prompts for reauthentication.  Login (successful), but fails to display chat - can't reconnect.  Logout, Log back in selecting cert and entering uname & pass - works.

#### Expected behavior
Reauthentication after session expires should use the cert and reconnect without issue.

**Comment by jeffg2k** [comment]
To add additional information.  The problem happens when the Connect screen transitions to the Login Screen, without first going to the Import Key screen.  If I logout and try to log back in without closing the application, it will skip the Import Key screen and sit at a "connecting.." state once logged in.  If I close out of the app after logout, it will ask me for the import key prior to the Login screen.

**Connect Screen**
![IMG_4481](https://user-images.githubusercontent.com/161904/76560067-b8f1e300-6476-11ea-98cf-f5379673e919.PNG)

**This should be the next screen, but sometimes if fails to come up (until you close the app).**

![IMG_4480](https://user-images.githubusercontent.com/161904/76560136-e474cd80-6476-11ea-8ccd-bc9680c98abf.PNG)

**Next we have the Login**
![IMG_4482](https://user-images.githubusercontent.com/161904/76560195-066e5000-6477-11ea-9450-0a45e4866348.PNG)

**When the Import Key screen fails to come up, I get this**
![IMG_4483](https://user-images.githubusercontent.com/161904/76560340-5a793480-6477-11ea-9caa-e1aa3d771f1b.PNG)

**Comment by larkox** [comment]
Closing due to the age of the issue. If this is still happening on the latest version, feel free to reopen.
