### ISSUE TITLE
trust certificat 

### ISSUE THREAD

**Issue by tclavier** [mattermost/mattermost-mobile#4796]
### Summary
The ssl certificat of my mattermost server is trust by TERENA. The application from playstore says my server is not correctly configured. And the application from fdroid says : cannot connect to the server.

![IMG_20200910_121541](https://user-images.githubusercontent.com/357257/92716647-6038cf80-f35f-11ea-8ffa-c5de1e73c4b8.jpg)

#### Environment Information

- Device Name: oneplus 6t
- OS Version: lineageos 17.1
- Mattermost App Version: 1.31.2
- Mattermost Server Version: 5.23.3

#### Steps to reproduce
Use https://mm-iutinfo.univ-lille.fr/

#### Expected behavior
I juste want to connect to my server :-)

#### Possible fixes
Use system certificat or add TERENA as trust certificat.

**Comment by enahum** [comment]
Your SSL certificate chain is incomplete!

https://www.ssllabs.com/ssltest/analyze.html?d=mm-iutinfo.univ-lille.fr

![image](https://user-images.githubusercontent.com/6757047/92722724-64a0c080-f33e-11ea-897c-ab99162b0572.jpeg)

**Comment by tclavier** [comment]
You write @enahum, it's possible to have only a warning ? with chrome and firefox, that work well :-(

**Comment by enahum** [comment]
@tclavier we attempted that in the forst place but came across a security issue and we decided against it. Anyway I think you’d be better off if the chain is fixed and complete.

**Comment by tclavier** [comment]
My admin has update the TLS configuration : 
![image](https://user-images.githubusercontent.com/357257/93208810-72e74600-f75d-11ea-91da-671d8f7f202a.png)

But i think it's a good idea to have a similar comportment between firefox and mattermost :-)

**Comment by enahum** [comment]
Glad it was resolved!

**Comment by tclavier** [comment]
I'm not agree with you, mattermost android application has not the same comportment than all navigators ... I thins it's a big problem, you can use Firefox or Chrome to go to a miss configured Mattermost and not with Android Application. IMHO it's a very bad user experience.

**Comment by enahum** [comment]
@tclavier although I understand where you’re coming from, the certificate restriction is applied by the operating systems. For example Android explains it [here](https://developer.android.com/training/articles/security-ssl#MissingCa).

The truth of the matter is that as long as the admin sets up the certificate correctly this should not happen and it wouldn’t be a bad experience for the user.

This issue is also addressed in our [documentation](https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection)
