### ISSUE TITLE
Error "Team could not be loaded " when logout

### ISSUE THREAD

**Issue by AiTranXuan** [mattermost/mattermost-mobile#4815]
#### Summary
Error "Team could not be loaded " when logout

#### Environment Information

- Device Name: Android/ IOS
- OS Version: 
- Mattermost App Version: 1.35
- Mattermost Server Version: 5.27

#### Steps to reproduce
Login to App and click logout in Setting Slidebar

#### Observed behavior
![D59E73ED-6E9C-458D-AFA6-FDAE629F6F13](https://user-images.githubusercontent.com/15552410/93416953-01c89f80-f8d1-11ea-9417-baecbbd24a93.jpg)

**Comment by amyblais** [comment]
@AiTranXuan 
1. Which login method do you use for Mattermost?
2. Is this a new issue in v1.35 for you?
3. What happens when you click on "Try again"?
4. Are there any other details that you'd be able to share about your environment or log errors?

**Comment by KheroNem** [comment]
Is there a fix for this bug ? for me the problem seems to appear when the function `resetState` of [global_event_handler](https://github.com/mattermost/mattermost-mobile/blob/release-1.35/app/init/global_event_handler.js) file for a reason the app launch an `getTeams()` request just after the call of this function.

**Comment by larkox** [comment]
This should be solved in V2. If the issue still reproduces, feel free to reopen the ticket.
