### ISSUE TITLE
Implement a font size setting or possibility to increase font inline

### ISSUE THREAD

**Issue by x9t9** [mattermost/mattermost-mobile#4922]
#### Summary

Font size option ( in the settings or inline ) is quite an important feature to increase accessibility for all users including vision impairment users on various levels.

#### Environment Information

This issue might be relevant on all screens depending on users .

#### Steps to reproduce
I think the issue is quit self - explanatory.

#### Expected behavior
Users should be able to increase ( or decrease ) the font size of the message depending on their comfort level paired with their vision.

#### Observed behavior
Font size can not be changes in the settings .

**Comment by CeesJol** [comment]
I see this issue is quite old, but as a suggestion: you can change the global font size of iOS in Settings > Accessibility, then select Display & Text Size. I can imagine that Android has similar functionality. By changing this, you can increase the font size. I think that this suffices as a font size option, what do you think? @x9t9

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
