### ISSUE TITLE
Our custom GUI can't be displayed on the mobile normally

### ISSUE THREAD

**Issue by UniverseOfTomorrow** [mattermost/mattermost-mobile#5350]
We have developed a system with the Web app plugins at Mattermost, but its custom GUI can not be displayed in the mobile client normally.
We learned that the full support for mobile plugins is still a work in progress from https://developers.mattermost.com/extend/plugins/mobile/ 
So we need to find a feasible solution. If you have  good ideas please contact me.

**Comment by larkox** [comment]
Right now there are no plans to support custom GUI on mobile due to technical limitations. There is an effort to increase the possibilities of integrations in mobile through the new concept of "apps": https://developers.mattermost.com/integrate/apps/

With apps you will be able to register buttons on certain parts of the interface so they can trigger actions, but not with the flexibility the web app plugins do. Nevertheless, hopefully is enough for your usecase.
