### ISSUE TITLE
Reauthenticate from stored token when app is reloaded

### ISSUE THREAD

**Issue by thomchop** [mattermost/mattermost-mobile#54]

**Comment by dmeza** [comment]
@thomchop: Storing the token and re-authenticating from stored token is working:
https://github.com/mattermost/mattermost-mobile/pull/78

Things that I think are missing but could go on a different tasks:
- SplashScreen that would be the actual initial screen
- Flag in config to jump the choose server screen
- Remove navbar and custom navbar, so that back button does not cause a conflict going back to the server screen
- When user clicks back (top left button) to Channels or Teams Screen. Click doesn't work.
