### ISSUE TITLE
Interactive dialog submission button not visible on mobile app

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-mobile#5543]
#### Summary
When opening an interactive dialog, the submission button is expected to be visible so the user can submit their choices. On the mobile app though, the button is not visible.

### Environment Information
  - Device Name: OnePlus 6
  - OS Version: Android 10
  - Mattermost App Version: 1.45 (12 July release)
  - Mattermost Server Version: 5.38

#### Steps to reproduce
1. Install any plugin which opens up an interactive dialog.
2. Trigger the interactive dialog.

#### Expected behavior
The dialog should have the submit button visible.

#### Observed behavior (that appears unintentional)
The dialog does not have the submit button visible.

See screenshots for reference.

In Mattermost mobile app-
![Screenshot_20210716-050008](https://user-images.githubusercontent.com/18575143/125870725-8b4df62b-8206-40c7-9eb2-0590cb3382db.jpg)

In Mattermost in mobile browser-
![Screenshot_20210716-050002](https://user-images.githubusercontent.com/18575143/125870730-516e0a60-e689-4653-87b1-9ba9f084d2bf.jpg)

**Comment by enahum** [comment]
@larkox ☝️

**Comment by amyblais** [comment]
@DHaussermann @larkox Are you able to reproduce and can you open a ticket?

**Comment by larkox** [comment]
I can reproduce, and looking at the code I am would say this is not a recent regression.
The problem is that the submission button is taking the label from the dialog definition. If the dialog has no `submit_label` property, the button shows no text (but it is still there).

I just submitted a PR.

@harshilsharma63 a quick fix for your integration is to add a `submit_label` to the dialog definition.

**Comment by harshilsharma63** [comment]
@larkox adding the `SubmitLabel` worked!

![Screenshot_20210720-165152](https://user-images.githubusercontent.com/18575143/126315970-0f832833-e844-4c6c-8f31-ba25c3b94654.jpg)
