### ISSUE TITLE
UI is not connecting to the server.

### ISSUE THREAD

**Issue by seansackowitz** [mattermost/mattermost-mobile#571]
#### Summary
States that is it always trying to connect when it is, and messages don't update.

#### Environment Information

- Device Name: HTC One (Although is also an issue on LG V20, and other Android devices)
- OS Version: 6.0.1
- Mattermost App Version: Latest released, and the testing version
- Mattermost Server Version: 3.9.0

#### Steps to reproduce
Launch the app, and log in.

#### Expected behavior
When you log in to a Mattermost server, you should expect it to connect right away, and update messages as they appear.

#### Observed behavior
There is a banner saying it is trying to connect, but it never goes away. Even when it has clearly connected successfully. Notifications show that a new message has arrived, however to see that message, you must force close the app and restart it before it will show up. Therefore, I surmise that the UI is not staying up to date with the actual data the phone is receiving.
![screenshot_20170525-212652](https://cloud.githubusercontent.com/assets/14167060/26477066/f4965dac-4190-11e7-9911-c21d0f70a265.png)

**Comment by enahum** [comment]
somehow your websocket is not connecting, can you please share the URL where you trying to connect and server logs?

**Comment by seansackowitz** [comment]
Ahh, I figured it out from looking in the logs... I was getting the `websocket: could not find connection header with token 'upgrade'` error, so I looked at my nginx proxy, and realized that api/v4 was not set up since upgrading to 3.9.0. Oversight of mine after upgrading the server. Thank you for the tip.

**Comment by jakew02** [comment]
@seansackowitz Hi, encountering the same problem as you (although everything works with api/v3 in my nginx config for the site), could you please share your nginx config for mm-3.9 with api v4 in your nginx config?

**Comment by seansackowitz** [comment]
https://docs.mattermost.com/install/install-ubuntu-1604.html#configuring-nginx-as-a-proxy-for-mattermost-server has the line of code to replace your v3 api with a location that can point to all versions of the api.

**Comment by licaon-kter** [comment]
Samsung 6.0.1
Mattermost v1.0.1
Mattermost server 4.0.1

Still having this issue, v1.0.1, log says:
`[EROR] /api/v3/general/ping:ServeHTTP code=501 rid=aaaaaaaaaaaaaaaaaaaaa uid= ip=DEVICE_IP API version 3 has been disabled on this server. Please use API version 4. See https://api.mattermost.com for details. [details: ]`

Server nginx setup is word-for-word as the link above (`location ~ /api/v[0-9]+/(users/)?websocket$` and all that)

Note that I had the app installed and logged in since before server version 3.9.0, albeit like the OP it would say it's not connected all the time (but actually work!). The server logs showed the error as above.

Now, I've just logged out and I can't login any more.
