### ISSUE TITLE
Unable to load channels with 1.0 (34)

### ISSUE THREAD

**Issue by WaLLy3K** [mattermost/mattermost-mobile#645]
#### Summary
When switching channels, the channel intermittently fails to load

#### Environment Information

- Device: iPhone8,1 (6S)
- Device Name: iPhone
- OS Version: 10.3.2
- Mattermost App Version: 1.0 (34)
- Mattermost Server Version: 3.8.0

#### Steps to reproduce
* Switch between various open channels, unable to reproduce issue
* Switch between various private channels, issue can *sometimes* be reproduced

I could reproduce it consistently yesterday, but today at time of writing, I'm not able to reproduce it at all.

#### Expected behavior
When switching between various channels, I expect to see the placeholder circle and rectangles and then have that fade away to the conversation at hand.

#### Observed behavior
When switching between various channels, I see the [placeholder circle/rectangles](http://i.imgur.com/kXd7D55.png), but it does not fade away to the conversation.

#### Possible fixes
I've suggested that server maintainer update to MatterMost 3.10.0.

**Comment by lfbrock** [comment]
Hi @WaLLy3K - thanks for the report!

We've had a couple other people seeing similar things - we think we may have fixed it as a side effect of this PR: https://github.com/mattermost/mattermost-mobile/pull/653

We'll be cutting a new build in the next day or two, it would be great if you could help test it once it's out and let us know if you see the issue anymore or not.

**Comment by WaLLy3K** [comment]
I can confirm I'm still seeing the issue, so I'll definitely hit that up when I see an update in TestFlight! Thanks @lfbrock

**Comment by Witcher42** [comment]
I think it's about `InteractionManager` of `channel_drawer`.

Sometimes, callbacks of runAfterInteractions won't be called after clicking a channel item, so posts of that channel won't be loaded.

This is because of [the reassignment of `openLeftHandle`](https://github.com/mattermost/mattermost-mobile/blob/master/app/components/channel_drawer/channel_drawer.js#L109). When swiping right to open the channel list, `handleDrawerOpenStart` will be called twice at the same time in some cases. That is `InteractionManager.createInteractionHandle` will be called twice,  and `this.openLeftHandle` is assigned twice.

After drawer's open action end, `handleDrawerOpen` will be called, however, only the last handle can be cleared by calling `InteractionManager.clearInteractionHandle`.

Here is a screenshot. Notice that handler 27 will never be cleared, so that React Native think animation is not finished yet and callback of `runAfterInteractions` won't be called.

![image](https://user-images.githubusercontent.com/1927546/27434469-5fb824e8-578b-11e7-8880-3f9651ac1457.png)
~ignore typo of the function names~

I don't know why this happens. I didn't make further test.


### Possible Solutions

#### The first solution

Use `if` to avoid reassignment, and make handler null after clearing.

In `handleDrawerOpenStart`:

```
        if (!this.openLeftHandle) {
            this.openLeftHandle = InteractionManager.createInteractionHandle();
        }
```

in `handleDrawerOpen`

```
        setTimeout(() => {
            if (this.openLeftHandle) {
                InteractionManager.clearInteractionHandle(this.openLeftHandle);
                this.openLeftHandle = null;
            }
        });
```

#### The second solution

Remove codes about `InteractionManager`. 

On my iPhone 6s, Mattermost works well. In fact, the first solution will cause some delay after clicking on channel item. The drawer started to close not immediately but about 300ms after clicking. If I use the second solution, drawer's close animation starts immediately and the animation is very smooth. Didn't test on other devices, don't know is there any problem on other devices.

**Comment by enahum** [comment]
Thanks guys for the report and a possible solution, there is a PR with a fix here https://github.com/mattermost/mattermost-mobile/pull/665/files#diff-8adfe070b0e342ec9f0fb3f1b8f354ac

@Witcher42 please feel free to make a PR whenever you see it fit, it will be much appreciated ;)

**Comment by enahum** [comment]
Closing via #655
