### ISSUE TITLE
Android app build failing

### ISSUE THREAD

**Issue by matthaios-easy-bi** [mattermost/mattermost-mobile#7150]
I’m having problem building android app. After completing all the steps and then running npm run build:android build fails on
Task :react-native-webrtc:compileDebugJavaWithJavac FAILED

there is a long list of errors all with org.webrtc does not exist

/mattermost-app/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java:5: error: package org.webrtc does not exist

I’m building it on M1 macOS, java 17.0.4.1, gradle 7.6

**Comment by enahum** [comment]
You should make sure the post install script is actually running, or manually execute `node node_modules/react-native-webrtc/tools/downloadWebRTC.js`

**Comment by matthaios-easy-bi** [comment]
Manually executing the script didn't help. Just to be clear what did you mean by "make sure the post install script is actually running"?

**Comment by enahum** [comment]
When you run `npm install` it executed a post install script that applies patches and other stuff.. you should make sure it is running correctly.

Also, f you ran the script manually and it did not help, then maybe you are sharing a different error.

I would encourage you to take the time to inspect the logs and determine what it may be the problem so that we can help you

**Comment by matthaios-easy-bi** [comment]
Build fails with this:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-webrtc:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

Beside org.webrtc does not exist there are also this cannot find symbol errors:

symbol:   class SurfaceTextureHelper
  location: class TrackPrivate
/mattermost-app/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java:469: error: cannot find symbol
            MediaStreamTrack track,

There are also some warnings about depricated functions in some of the steps but these above are only errors

**Comment by uusijani** [comment]
I have the same issue. I'm doing this in a Linux container (Ubuntu 20.04 inside Ubuntu 20.04), but like matthaios-easy-bi, I'm using `npm run build:android` to build ([as per documentation](https://developers.mattermost.com/contribute/more-info/mobile/build-your-own/android/#build-the-mobile-app)). This has worked up until 2.0, but with 2.1 it always fails due to non-existent org.webrtc. Manually running `npm install` prior to `npm run build:android` makes no difference, nor does `node node_modules/react-native-webrtc/tools/downloadWebRTC.js` (although it does seemingly download the package successfully).

[Here's excerpts from the build output](https://github.com/mattermost/mattermost-mobile/files/10824122/excerpt.log).
