### ISSUE TITLE
Is it possible to block acces via browser and only allow outside acces for the mobile apps?

### ISSUE THREAD

**Issue by BobWs** [mattermost/mattermost-mobile#7259]
Hello, 
I'm wondering if it's feasible to restrict external access via browser. I intend to only allow external access through mobile applications. I've unsuccessfully attempted to accomplish this in Nginx-Proxy-Manager by blocking the /login location. Can anyone advise on whether this is possible and how I should configure this via reverse proxy?

**Comment by BobWs** [comment]
Thanks for the detailed explanation, it is indeed a bit overkill and to much hassle.😏

**Comment by larkox** [comment]
A simpler but "bad" solution may be a filtering on the user agent. Most mobile browsers, one way or another, add to their user agent whether they are a iOS or Android device. If you were able to find the correct things to check, in theory you could block that on your side.

That being said, any user-agent based approach is brittle to say the least, and changes both in Mattermost user agent string or the browsers user agent string may change your expected behavior.
