### ISSUE TITLE
HELP: Failed to send FCM push in Android

### ISSUE THREAD

**Issue by gamestap99** [mattermost/mattermost-mobile#7652]
Hello on this beautiful day, I decided to upgrade the version. However, I encountered an issue that prevents Android from receiving notification messages. Even on iOS, there was a similar issue, but after reading the issues in github, I decided to push it to the store and it worked. Now, the only remaining issue is with Android. Please help me!

-- Platform:

- MattermostMobile: v2.9.0
- mattermost-push-proxy:5.26.0

-- Error
![Screenshot 2023-11-07 at 17 31 40](https://github.com/mattermost/mattermost/assets/43195138/d212a832-da66-4074-b278-08312f6d7f16)

**Comment by amyblais** [comment]
Hi @gamestap99, have you tried this document for troubleshooting push notifications https://docs.mattermost.com/deploy/mobile-troubleshoot-notifications.html?

**Comment by jibinjosephjmj** [comment]
Hey @gamestap99 , did you able to solve the issue..I got similar error when I tried to upgrade mattermost push proxy to the latest one.The configurations are done as per the documentation.. But, the exact similar error message is what I got.. Any help is really helpful

**Comment by jibinmj** [comment]
@amyblais I also get similar error..Please help me since the Old version is deprecated in FCM I really want new HTTP V1 upgraded the service but error throws like this
curl http://10.50.8.144:8066/api/v1/send_push -X POST -H "Content-Type: application/json" -d '{"type": "message", "message": "test", "badge": 1, "platform": "android", "server_id": "z4395g3upfgeux5u5ymmtsgs9h", "device_id": "cTubWaBwRWGa1CKSEhqsd8:APA91bGRQH63lLPl5eKYiYk2Tlf1jIvAZnHsRpRx-8FvnewIgYMhMB2L5Nll338R-F2W7G_ULeo4L1uheM5R696UOBTfWUq4KJDU8B2aZ7jLn7CUPF69v1AKNI3Y9pvQNmtq0W1UBj8k", "channel_id": "9eykqfegi3nddrdkf59akxg13w"}'
{"error":"context deadline exceeded","status":"FAIL"}

**Comment by gamestap99** [comment]
@amyblais @jibinmj  thanks
