### ISSUE TITLE
Google Play Store Description Shows incorrect required Server Version

### ISSUE THREAD

**Issue by egret85** [mattermost/mattermost-mobile#830]
The application page in the Google Play store for v1.1.0 says "To use this app, you need the URL for a v3.7+ Mattermost server."  The Changelog on github for v1.1 says "Server Versions Supported: Server v3.10+ is required".  Trying to connect to a v3.9 server with the v1.1 android app gives a server version error.  The Play Store description should be updated to reflect the new server version requirement for the latest version of the app.

**Comment by lfbrock** [comment]
Thanks! 

I think this should be fixed now, turns out it was being overwritten by our automation for submitting to play store. I've added a note to our process to update [this file](https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/metadata/android/en-US/full_description.txt) to make sure it doesn't happen again.
