### ISSUE TITLE
iOS Client - Sometimes it Takes up to 20 seconds till the client connects.

### ISSUE THREAD

**Issue by lfalkenburg** [mattermost/mattermost-mobile#847]
#### Summary
Sometimes it Takes up to 20 seconds till the client connects. Procedere: hitting a push message in Notification Center, client openes and then I wait until it gets ‚green‘ and messages been loaded.

#### Environment Information

- Device Name: iPhone 7 Plus
- OS Version: 11.x (beta)
- Mattermost App Version: 1.0 (Build 34)
- Mattermost Server Version: 4.0.0  (4.0.2) 

Protocol says: Errors:
[{"line":423,"column":6987,"sourceURL":"file:///var/containers/Bundle/Application/DB7D4666-DC58-40C1-B0B7-B686836FC48B/Mattermost.app/main.jsbundle"}]

#### Steps to reproduce
Open Mattermost Client.

#### Expected behavior
Client opens and should quickly load messages and/or connects to the server within a few (2-4?) Seconds.

#### Observed behavior
Most of the time, I wait "hours" (up to 20 seconds) till the client is connected and messages are shown/loaded

#### Possible fixes
Non from my side.

**Comment by mkozjak** [comment]
What's up with this?
I get this for each channel change...

**Comment by JohnOCFII** [comment]
Seeing this regularly against a 4.0.2 server as well.

**Comment by lfbrock** [comment]
Hi everyone, thanks for the feedback. We're going to discuss it this week to see what we can do about it, will post back here with the results of the discussion.

**Comment by lfbrock** [comment]
Hey everyone - just an update on this. 

We've made a few changes we hope will help address this issue for the upcoming release (v1.3, around Oct 5) and will be continuing to work on performance for the release after as well. 

I'm going to close this issue since the push notification issue described should be fixed, but if you see this after the next release please help open another GitHub issue, or comment on this forum post describing what you see? 

https://forum.mattermost.org/t/reports-of-slowness-in-mattermost-mobile-apps/3827/10
